### PR TITLE
Elemental 4.x support

### PR DESCRIPTION
**Pull request by chillu**
Also changing language defaults to English,
and supporting German through a lang file :)

### CODE REVIEW

**Comment by chillu** [comment]
Ping :)

**Comment by maxime-rainville** [comment]
Is this meant to be hosted on the open-sausage repo? Shouldn't the PR be against the original repo?

**Comment by chillu** [comment]
lol, fail...

**Comment by chillu** [comment]
https://github.com/derralf/silverstripe-elemental-call-to-action/pull/1

**Pull request closed without merging**
